import type { DrugGeneRule } from "./types"

export const DRUG_GENE_RULES: Record<string, DrugGeneRule> = {
  Codeine: {
    gene: "CYP2D6",
    rsids: ["rs3892097", "rs1065852", "rs1080985", "rs16947", "rs28371725"],
    starAlleles: {
      "*1": ["rs3892097:CC", "rs1065852:CC"],
      "*2": ["rs16947:GA"],
      "*4": ["rs3892097:GA", "rs3892097:AA"],
      "*5": [],
      "*6": ["rs1065852:GA", "rs1065852:AA"],
      "*10": ["rs1065852:CT"],
      "*17": ["rs28371725:GA"],
      "*41": ["rs28371725:CT"],
    },
    phenotypeMap: {
      "*1/*1": "NM",
      "*1/*2": "NM",
      "*2/*2": "NM",
      "*1/*4": "IM",
      "*1/*10": "IM",
      "*1/*41": "IM",
      "*4/*4": "PM",
      "*4/*6": "PM",
      "*6/*6": "PM",
      "*1/*17": "IM",
      "*2/*41": "IM",
    },
    riskMap: {
      PM: "Contraindicated",
      IM: "Adjust Dosage",
      NM: "Safe",
      RM: "Monitor Closely",
      URM: "Toxic",
      Unknown: "Monitor Closely",
    },
    cpicLevel: "A",
    recommendations: {
      PM: "Avoid codeine. Use non-tramadol, non-codeine analgesic. CYP2D6 poor metabolizers cannot convert codeine to morphine.",
      IM: "Use codeine with caution at reduced dose. Consider alternative analgesic. Monitor for reduced efficacy.",
      NM: "Use codeine at standard dosage per clinical guidelines.",
      RM: "Use codeine with monitoring. May have enhanced response.",
      URM: "Avoid codeine. Ultrarapid metabolism leads to toxic morphine levels. Use non-opioid alternative.",
      Unknown: "Insufficient data. Use codeine with caution and enhanced monitoring.",
    },
    alternatives: ["Acetaminophen", "Ibuprofen", "Morphine (with dose adjustment)"],
    monitoring: {
      PM: "Monitor for pain control with alternative analgesic.",
      IM: "Monitor pain control and consider dose titration.",
      NM: "Standard monitoring per clinical practice.",
      RM: "Monitor for enhanced opioid effects and respiratory depression.",
      URM: "If codeine must be used, monitor closely for toxicity signs.",
      Unknown: "Enhanced monitoring recommended until phenotype clarified.",
    },
  },
  Clopidogrel: {
    gene: "CYP2C19",
    rsids: ["rs4244285", "rs4986893", "rs12248560", "rs28399504"],
    starAlleles: {
      "*1": ["rs4244285:GG", "rs4986893:GG"],
      "*2": ["rs4244285:GA", "rs4244285:AA"],
      "*3": ["rs4986893:GA", "rs4986893:AA"],
      "*17": ["rs12248560:CT", "rs12248560:TT"],
    },
    phenotypeMap: {
      "*1/*1": "NM",
      "*1/*2": "IM",
      "*1/*3": "IM",
      "*2/*2": "PM",
      "*2/*3": "PM",
      "*3/*3": "PM",
      "*1/*17": "RM",
      "*17/*17": "URM",
    },
    riskMap: {
      PM: "Contraindicated",
      IM: "Adjust Dosage",
      NM: "Safe",
      RM: "Safe",
      URM: "Monitor Closely",
      Unknown: "Monitor Closely",
    },
    cpicLevel: "A",
    recommendations: {
      PM: "Avoid clopidogrel. Use prasugrel or ticagrelor. Poor metabolizers have significantly reduced antiplatelet effect.",
      IM: "Consider alternative antiplatelet therapy or increased dose with monitoring.",
      NM: "Use clopidogrel at standard dosage.",
      RM: "Use clopidogrel at standard dosage. Enhanced activation expected.",
      URM: "Use clopidogrel with monitoring for increased bleeding risk.",
      Unknown: "Consider alternative or use with enhanced platelet monitoring.",
    },
    alternatives: ["Prasugrel", "Ticagrelor"],
    monitoring: {
      PM: "Use alternative antiplatelet. Monitor cardiovascular events.",
      IM: "Platelet function testing recommended.",
      NM: "Standard cardiovascular monitoring.",
      RM: "Standard monitoring. Watch for bleeding.",
      URM: "Enhanced monitoring for bleeding complications.",
      Unknown: "Platelet function testing and clinical monitoring.",
    },
  },
  Warfarin: {
    gene: "CYP2C9",
    rsids: ["rs1799853", "rs1057910", "rs9923231"],
    starAlleles: {
      "*1": ["rs1799853:CC", "rs1057910:AA"],
      "*2": ["rs1799853:CT", "rs1799853:TT"],
      "*3": ["rs1057910:AC", "rs1057910:CC"],
    },
    phenotypeMap: {
      "*1/*1": "NM",
      "*1/*2": "IM",
      "*1/*3": "IM",
      "*2/*2": "PM",
      "*2/*3": "PM",
      "*3/*3": "PM",
    },
    riskMap: {
      PM: "Toxic",
      IM: "Adjust Dosage",
      NM: "Safe",
      RM: "Safe",
      URM: "Safe",
      Unknown: "Monitor Closely",
    },
    cpicLevel: "A",
    recommendations: {
      PM: "Significantly reduce warfarin dose. High bleeding risk. Consider VKORC1 genotype for dosing.",
      IM: "Reduce warfarin dose by 20-40%. Monitor INR closely during initiation.",
      NM: "Standard warfarin dosing with routine INR monitoring.",
      RM: "Standard dosing. Normal metabolism expected.",
      URM: "Standard dosing. Normal metabolism expected.",
      Unknown: "Initiate at low dose with frequent INR monitoring.",
    },
    alternatives: ["Rivaroxaban", "Apixaban", "Dabigatran"],
    monitoring: {
      PM: "Frequent INR monitoring. Watch for bleeding signs.",
      IM: "INR monitoring every 1-2 weeks during dose adjustment.",
      NM: "Routine INR monitoring per guidelines.",
      RM: "Routine INR monitoring.",
      URM: "Routine INR monitoring.",
      Unknown: "Frequent INR monitoring until stable.",
    },
  },
  Mercaptopurine: {
    gene: "TPMT",
    rsids: ["rs1800462", "rs1800460", "rs1142345"],
    starAlleles: {
      "*1": ["rs1800462:CC", "rs1800460:CC", "rs1142345:AA"],
      "*2": ["rs1800462:CG", "rs1800462:GG"],
      "*3A": ["rs1800460:CT", "rs1142345:AG"],
      "*3B": ["rs1800460:CT", "rs1800460:TT"],
      "*3C": ["rs1142345:AG", "rs1142345:GG"],
    },
    phenotypeMap: {
      "*1/*1": "NM",
      "*1/*3A": "IM",
      "*1/*3B": "IM",
      "*1/*3C": "IM",
      "*1/*2": "IM",
      "*3A/*3A": "PM",
      "*3C/*3C": "PM",
      "*2/*3A": "PM",
    },
    riskMap: {
      PM: "Contraindicated",
      IM: "Adjust Dosage",
      NM: "Safe",
      RM: "Safe",
      URM: "Safe",
      Unknown: "Monitor Closely",
    },
    cpicLevel: "A",
    recommendations: {
      PM: "Drastically reduce dose (10x reduction) or use alternative. High risk of fatal myelosuppression.",
      IM: "Reduce starting dose by 30-70%. Monitor for myelosuppression.",
      NM: "Standard dose per protocol.",
      RM: "Standard dosing.",
      URM: "Standard dosing.",
      Unknown: "Start at reduced dose and titrate with monitoring.",
    },
    alternatives: ["Mycophenolate mofetil (context-dependent)"],
    monitoring: {
      PM: "Weekly CBC for at least 8 weeks. Watch for myelosuppression.",
      IM: "CBC every 1-2 weeks during initiation.",
      NM: "Standard CBC monitoring per protocol.",
      RM: "Standard monitoring.",
      URM: "Standard monitoring.",
      Unknown: "Frequent CBC monitoring.",
    },
  },
  Azathioprine: {
    gene: "TPMT",
    rsids: ["rs1800462", "rs1800460", "rs1142345"],
    starAlleles: {
      "*1": ["rs1800462:CC", "rs1800460:CC", "rs1142345:AA"],
      "*2": ["rs1800462:CG", "rs1800462:GG"],
      "*3A": ["rs1800460:CT", "rs1142345:AG"],
      "*3B": ["rs1800460:CT", "rs1800460:TT"],
      "*3C": ["rs1142345:AG", "rs1142345:GG"],
    },
    phenotypeMap: {
      "*1/*1": "NM",
      "*1/*3A": "IM",
      "*1/*3B": "IM",
      "*1/*3C": "IM",
      "*1/*2": "IM",
      "*3A/*3A": "PM",
      "*3C/*3C": "PM",
      "*2/*3A": "PM",
    },
    riskMap: {
      PM: "Contraindicated",
      IM: "Adjust Dosage",
      NM: "Safe",
      RM: "Safe",
      URM: "Safe",
      Unknown: "Monitor Closely",
    },
    cpicLevel: "A",
    recommendations: {
      PM: "Avoid or drastically reduce dose. Fatal myelosuppression risk.",
      IM: "Reduce starting dose by 30-70%. Close hematological monitoring.",
      NM: "Standard dosing per protocol.",
      RM: "Standard dosing.",
      URM: "Standard dosing.",
      Unknown: "Start at reduced dose with monitoring.",
    },
    alternatives: ["Mycophenolate mofetil"],
    monitoring: {
      PM: "Weekly CBC for at least 8 weeks.",
      IM: "CBC every 1-2 weeks during initiation.",
      NM: "Standard monitoring.",
      RM: "Standard monitoring.",
      URM: "Standard monitoring.",
      Unknown: "Frequent CBC monitoring.",
    },
  },
  Simvastatin: {
    gene: "SLCO1B1",
    rsids: ["rs4149056"],
    starAlleles: {
      "*1a": ["rs4149056:TT"],
      "*5": ["rs4149056:TC"],
      "*15": ["rs4149056:CC"],
    },
    phenotypeMap: {
      "*1a/*1a": "NM",
      "*1a/*5": "IM",
      "*1a/*15": "IM",
      "*5/*5": "PM",
      "*5/*15": "PM",
      "*15/*15": "PM",
    },
    riskMap: {
      PM: "Contraindicated",
      IM: "Adjust Dosage",
      NM: "Safe",
      RM: "Safe",
      URM: "Safe",
      Unknown: "Monitor Closely",
    },
    cpicLevel: "A",
    recommendations: {
      PM: "Avoid simvastatin. High risk of myopathy/rhabdomyolysis. Use alternative statin.",
      IM: "Use simvastatin at lower dose (max 20mg) or consider alternative statin.",
      NM: "Standard dosing per clinical guidelines.",
      RM: "Standard dosing.",
      URM: "Standard dosing.",
      Unknown: "Use lower dose with CK monitoring.",
    },
    alternatives: ["Rosuvastatin", "Pravastatin", "Fluvastatin"],
    monitoring: {
      PM: "CK monitoring with alternative statin. Watch for muscle symptoms.",
      IM: "CK monitoring. Report muscle pain/weakness immediately.",
      NM: "Standard lipid panel monitoring.",
      RM: "Standard monitoring.",
      URM: "Standard monitoring.",
      Unknown: "CK monitoring and muscle symptom assessment.",
    },
  },
}
